# Tables, Trees, and Triples


## Chapter 

Forthcoming

## Lecture

Forthcoming 

---

## Readings
Our readings this week are from the W3C standard for `Data on the Web`. W3C is the World Wide Web Consortium - the main standardization organization for web technologies. In 2017 a working group of experts in data curation came together to develop a set of best practices for structuring, publishing, and making data on the web accessible. T  

- Lóscio et al (2017) Data on the Web - Best Practices. https://www.w3.org/TR/dwbp/
- Read one additional Data on the Web - Use Case from this list: https://www.w3.org/TR/dwbp-ucr/

In future weeks we will use the Data on the Web primer for activities related to our data curation protocol.

For a bit of historical background, Ch 1 of this book (pages 1-13) provides an excellent overview of how data were originally made compliant with web standards. The rest of the book also provides a great overview of data models and database integration more generally, but it is very much a lengthy and time intensive read:

- Abiteboul, S., Buneman, P., & Suciu, D. (2000). Data on the Web: from relations to semistructured data and XML. Morgan Kaufmann. 

[PDF](https://homepages.dcc.ufmg.br/~laender/material/Data-on-the-Web-Skeleton.pdf)

## Exercise
Chances are if you are living under quarantine (Spoiler: We all are!) you have taken up a new hobby to preoccupy yourself. Maybe this is something productive like knitting or pilates. Maybe it is something like baking sourdough bread (Spoiler: So is the rest of the internet!). In preparation for our class on `Tidy Data` next week we will attempt to add some structure to a rather innocuous piece of information that is published to the web and that you're likely to be encountering with your new found quarantine hobby: Chocolate Chip Cookie recipes.

This [infographic](https://d3vjjov8ymzzxi.cloudfront.net/chefsteps-com-files/chefsteps-cookie-table.pdf) from ChefSteps provides a "parametric" explanation of different approaches to making a chocolate chip cookie ^[[Jenny Bryan](https://jennybryan.org/about/) pointed out this example and provided the data we will use next week in our `Tidy Data` exercise].

Your assignment for next week is to look at the infographic, and choose one cookie. Decide how you would structure the information in this graphic so that it could be interpretable in a table form - that is, each cookie has set of attributes and values that follows a common scheme. This scheme can likely be applied to any cookie and its recipe. There is already a good deal of structure to this data, but there are some very strange and confusing choices in the values that will complicate choosing a common structure. Do your best to come up with a structure that seems generalizable to any cookie.
