# Metadata Application Profiles

## Chapter
Forthcoming

## Lecture
Forthcoming

## Exercise
The exercise for this week is to work on your protocol, and in particular [Assignment](https://nniiicc.github.io/LIS-598-DC2-Sp2020/protocol-assignment.html#assignment-5-metadata-application-profiles) 5 which deals with metadata application profiles. Your readings this week describe metadata application profiles in detail. 

## Reading

Application profiles:

- Heery, R., & Patel, M. (2000). Application profiles: mixing and matching metadata schemas. Ariadne, (25). http://www.ariadne.ac.uk/issue/25/app-profiles/ 

- [The Singapore Framework for Application Profiles](https://www.dublincore.org/specifications/dublin-core/singapore-framework/). Note this is currently under revision by DCMI. You can catch up on their work here https://github.com/dcmi/dcap  (and also see an example of `use cases` in the wild)

Some examples of metadata application profiles:

- DPLA https://drive.google.com/file/d/1fJEWhnYy5Ch7_ef_-V48-FAViA72OieG/view
- Cornell Library https://confluence.cornell.edu/display/mwgweb/CUL+Metadata+Application+Profiles
- Carnegie Hall Archives https://carnegiehall.github.io/digitalcolls-metadataprofile/

Relevant (optional) readings:

- Hebron, T. K. (2018). Extending and Adapting Metadata Audit Tools for Mountain West Digital Library Members Code4Lib Journal, (41). https://journal.code4lib.org/articles/13632 
- Curado Malta, M., Bermúdez Sabel, H., Baptista, A. A., & González-Blanco García, E. (2018). Validation of a metadata application profile domain model. http://e-spacio.uned.es/fez/view/bibliuned:363-Egonzalez15 

Case Study for discussion (optional):

- Stein, A., & Dunham, E. (2018). Meaningful Data Sharing: Developing the Illinois Data Bank Metadata Framework. Journal of Library Metadata, 18(2), 59-83. https://www.ideals.illinois.edu/handle/2142/103173 
